apiVersion: v1
kind: Secret
metadata:
  name: git-repo-secret
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  name: cmhhY20=
  password: Z2hwXzhIUmwydlU3alRrVTBWZGlWQkx0ZXJJS1kzSTFmTjJHTEYybQ==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2VsZWN0cm9uMTE2Mi9naXRvcHMuZ2l0Cg==
  username: ZWxlY3Ryb24xMTYy
type: Opaque