apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-customrole
  annotations:
    argocd.argoproj.io/sync-wave: "4"
rules:
- apiGroups:
  - "*"
  resources: ["*"]
  verbs: ["*"]