apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
patches:
  - target:
      version: v1
      kind: Secret
      name: git-repo-secret
    patch: |-
      - op: replace
        path: /data/password
        value: Z2hwXzhIUmwydlU3alRrVTBWZGlWQkx0ZXJJS1kzSTFmTjJHTEYybQ==